---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600

- name: install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - python-pip
    - python-dev

- name: install python module consulate
  pip: >
    name={{item}}
  with_items:
    - tornado
    - consulate
